# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: c128146
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
advanced: false
docs_engine: MYST
github_repo_name: propshop
include_funding: true
override: true
override_codecov: false
override_coveragerc: false
override_env: false
override_flake8: false
override_gitattributes: false
override_gitignore: false
override_isort: true
override_markdownlint: false
override_precommit: false
override_pyrightconfig: false
override_pytest: false
override_sourcery: false
override_update: false
override_vscode_extensions: false
override_vscode_launch: false
override_vscode_settings: false
override_vscode_tasks: false
project_email: blake.naccarato+propshop@gmail.com
project_name: propshop
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.10'
use_dvc: false
year_of_project_creation: 2022
