version: "1"

ignore:
  # The defaults
  - ".git"
  - "venv"
  - ".venv"
  - "env"
  - ".env"
  - ".tox"
  - "node_modules"
  - "vendor"
  # Extras
  - ".*"

rule_settings:
  python_version: "3.10"
  enable: ["default"]
  disable:
    - "remove-redundant-constructor-in-dict-union" # Explicit dict(zip(...)) is better
