name: "bump"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["requirements.txt"]

jobs:
  bump:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.11"
        with:
          python-version: "3.10"
          # Don't `pip install .` to avoid dependency cycle
          install-project: false
      - run: "python .tools/scripts/bump_pyproject.py"
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Bump `pyproject.toml` dependencies"
