name: changerelease
on:
  workflow_dispatch: {}
  push:
    paths: [CHANGELOG.md]
    branches: [main]
    tags: ["*"]

jobs:
  sync:
    runs-on: ubuntu-20.04
    steps:
      - uses: dropseed/changerelease@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
