name: main

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake8:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: bash .tools/scripts/cicd_setup.sh
      - run: flake8

  pyright:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: bash .tools/scripts/cicd_setup.sh
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 14
      - run: npm install
      - run: node_modules/.bin/pyright

  pytest-cov:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: bash .tools/scripts/cicd_setup.sh
      - run: pytest --cov
      - uses: codecov/codecov-action@v3.1.0
