name: "main"

on: ["push", "workflow_dispatch"]

jobs:
  pyright:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: pyright
  ruff:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: "ruff --no-fix --output-format github ."
  pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
      - run: "pytest --cov"
      - uses: "codecov/codecov-action@v3.1.4"
  bump_project:
    needs: ["pyright", "ruff", "pytest"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.2.3"
        with:
          python-version: "3.11"
          install-project: false
      - uses: "stefanzweifel/git-auto-commit-action@v5.0.0"
        with:
          commit_message: "Update project."
