name: publish
on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.2
        with:
          python-version: "3.10"
      - run: bash tooling/cicd_setup.sh
      - name: publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
        run: flit publish
